services:
    sonata.admin.post:
        class: Shareit\BackOfficeBundle\Admin\PostAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: "Content", label: "Post" }
        arguments:
            - ~
            - Shareit\MainBundle\Entity\Post
            - ~
        calls:
            - [ setTranslationDomain, [BackOfficeBundle]]