security:
    encoders:
        Symfony\Component\Security\Core\User\User:
          algorithm: sha1
          encode_as_base64: false
          iterations: 1
        ShareItMainBundle\Entity\User:
          algorithm: sha1
          encode_as_base64: false
          iterations: 1

    role_hierarchy:
        ROLE_USER:       ROLE_USER
        ROLE_ADMIN: [ROLE_USER, ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

    providers:
        in_memory:
            memory:
                users:
                    user:  { password: 39e21432a7dcba489697b4ef779f4b0c6f08b89f, roles: [ 'ROLE_USER' ] }
                    admin: { password: 39e21432a7dcba489697b4ef779f4b0c6f08b89f, roles: [ 'ROLE_ADMIN' ] }

    firewalls:
        dev:
            pattern:  ^/(_(profiler|wdt)|css|images|js)/
            security: false

        login:
            pattern:  ^/demo/secured/login$
            security: false

        backoffice:
            pattern:    ^/admin
            form_login:
                check_path: /admin/login_check
                login_path: /admin/backoffice-login
                default_target_path: /admin/dashboard
                always_use_default_target_path: true
            logout:
                path:   /admin/logout
                target: /admin/backoffice-login
            anonymous: ~
            #http_basic:
            #    realm: "Secured Demo Area"

    access_control:
        - { path: ^/admin/backoffice-login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/admin, roles: ROLE_ADMIN }
        #- { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY, requires_channel: https }
