registration:
    pattern:  /register
    defaults: { _controller: ShareitMainBundle:Registration:register }

homepage:
    pattern:  /
    defaults: { _controller: ShareitMainBundle:Homepage:index }

fo_login:
    pattern: /login
    defaults: { _controller: ShareitMainBundle:Registration:login }

fo_login_check:
    pattern: /login_check

fo_logout:
    pattern: /logout