Shareit\MainBundle\Entity\Domain:
    type: entity
    table: domains
    fields:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
        name:
            type: string
            length: 255
        shortDescription:
            type: string
            length: 150
        description:
            type: text
            length: 1500
        createdAt:
            type: datetime
        nrOfFollowers:
            type: integer
    lifecycleCallbacks: {  }
