Shareit\MainBundle\Entity\Post:
    type: entity
    table: posts
    fields:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
        createdAt:
            type: datetime
        updatedAt:
            type: datetime
        likes:
            type: integer
        unlikes:
            type: integer
        title:
            string: 255
        text:
            type: text
    manyToOne:
        user:
            targetEntity: User
            inversedBy: posts
    oneToMany:
        comments:
            targetEntity: Comment
            mappedBy: post
    lifecycleCallbacks: {  }
